# Generated by Django 2.1.4 on 2019-01-10 14:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190110_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 10, 14, 22, 41, 629385, tzinfo=utc)),
        ),
    ]
